### ISSUE TITLE
Need to change the styling to be consistent across all of the pages

### ISSUE THREAD

**Issue by BMaggi-UTS** [AkramHamd/IoTBay#2]
At the moment objects like NAV, are dependent on the individual page stylesheets. It would be much more efficient to create one stylesheet that contains styles for all the pages, so that one page is equally replicated across all pages in terms of styling.

**Comment by amadywr** [comment]
I have created a layout css file that should keep things consistent across the application. whenever a new jsp file is created layout.css should be added in addition to css file made just for that file.
